# Generated by Django 4.0.4 on 2022-04-14 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=64)),
                ('activity_image', models.ImageField(blank=True, null=True, upload_to='activity')),
                ('active', models.BooleanField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('surname', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('authorized', models.CharField(max_length=64)),
                ('org_image', models.ImageField(blank=True, null=True, upload_to='organization')),
                ('address', models.TextField()),
                ('org_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('university', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('edu_deg', models.CharField(choices=[('lisans', 'lisans'), ('yükseklisans', 'yükseklisans'), ('doktora', 'doktora'), ('mezun', 'mezun')], max_length=64)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=32)),
                ('activity_name', models.ManyToManyField(to='Certificate.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('host_image', models.ImageField(blank=True, null=True, upload_to='host')),
                ('activity_name', models.ManyToManyField(to='Certificate.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cer_code', models.AutoField(primary_key=True, serialize=False, verbose_name='certificate ID')),
                ('cer_name', models.CharField(max_length=64)),
                ('cer_deg', models.CharField(choices=[('Certificate of Participation ', 'Certificate of Participation'), ('Certificate of Achievement', 'Certificate of Achievement'), ('Aword Certificate', 'Aword Certificate')], max_length=64)),
                ('active', models.IntegerField(blank=True, choices=[(0, 'Inactive'), (1, 'Active')], default=0, null=True)),
                ('cer_description', models.TextField()),
                ('activity_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Certificate.activity')),
                ('organisation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate.organization')),
                ('participant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate.participant')),
            ],
            options={
                'ordering': ['cer_name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='org_name',
            field=models.ManyToManyField(to='Certificate.organization'),
        ),
    ]
