# Generated by Django 3.2.6 on 2022-04-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': [-1]},
        ),
    ]
